### ISSUE TITLE
Sometimes sync just stops working and a complete re-sync is necessary

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-node#86]
I'm not sure what actually causes this, but every once in a while the node just stops syncing and goes into a loop of the same blocks. The only solution I've found to resolve this is to just re-initialize the blockchain folder and start over. Are we doing something wrong here or is this a known behavior?

**Comment by evoskuil** [comment]
I can't say without more information...

* It could be that you have not adjusted your configuration following initial block download and are running with a size one block pool. That would make it impossible to clear any reorganization. https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings#default-settings
* Or it could be that there is a bug causing the node to be unable to validate a certain block.
* Or it could be that you have suffered a chain corruption due to a hard shutdown, and there is missing transaction information that makes it impossible to validate a block.

I have seen each of these, but I'm not aware of any bug at this point. The debug log would make it easy to answer.

**Comment by hoffmabc** [comment]
I'm sorry I also meant to clarify this is on testnet. Mainnet keeps plugging away just fine.

**Comment by evoskuil** [comment]
I've seen no difference in behavior WRT choice of network. Do you have debug  data from the time period of the stall?

**Comment by evoskuil** [comment]
Or could you tell me the hash of the last block synced as reported in the log or console?

**Comment by hoffmabc** [comment]
```
11:22:53.345067 WARNING [network] Invalid payload from [[::]] operation failed
11:25:02.228768 WARNING [network] Invalid payload from [[::]] operation failed
12:01:04.855224 WARNING [validate] Invalid block [00000000000002f033d89f472985cc680bdc2a4a69a289ff0bd960d11d24f94c] size limits failed
12:01:04.864877 ERROR [poller] Error storing block [00000000000002f033d89f472985cc680bdc2a4a69a289ff0bd960d11d24f94c] size limits failed
```

**Comment by evoskuil** [comment]
The first two warnings are fine and not related to the last two. The last warning/error is a pair that results from a block that is in fact invalid:

https://www.blocktrail.com/tBTC/block/00000000000002f033d89f472985cc680bdc2a4a69a289ff0bd960d11d24f94c

Presumably the error is giving the correct reason and it is invalid due to block size. I can't say for sure without a copy of the block.

If you only get this error once it would not result in the behavior you described above. Is this error repeating? If so you are somehow only connecting to peers that are feeding the same invalid block - which seems unlikely. So something doesn't add up.

**Comment by evoskuil** [comment]
@hoffmabc Any new info on this?

**Comment by hoffmabc** [comment]
The issue was the debug.log got so huge it just stopped. Once deleted and the server restarted it worked again. The server does get a block or two behind every few hours but gets back in line quickly.
